### ISSUE TITLE
Graphical issues on Safari iOS 11

### ISSUE THREAD

**Issue by adoniskrasniqi** [cyanharlow/purecss-francine#8] opened 2018-05-02 09:24 UTC
![ac22abb3-79a4-44b8-863f-a1274b0719cc](https://user-images.githubusercontent.com/17968705/39515697-326e4ef6-4dfb-11e8-9bf1-42cdbe9721c3.png)

**Comment by adi518** [comment] 2018-05-02 10:16
It looks like Safari made her frown _and_ angry.

**Comment by BramVanBerkel** [comment] 2018-05-02 10:55
I can’t open it at all on IOS Safari

**Comment by makc** [comment] 2018-05-02 11:38
this is duplicate of #5 actually

**Comment by adoniskrasniqi** [comment] 2018-05-02 18:33
@makc 
Different browser.

**Comment by happychameleon** [comment] 2018-05-02 20:27
@adoniskrasniqi 
but the same web engine (because all browsers on iOS are forced to use the safari web-kit engine)

**Closed** 2018-05-02 20:29 UTC

**Comment by adoniskrasniqi** [comment] 2018-05-02 20:30
Closed because it is duplicate of #5
Thanks to @makc and @happychameleon
